// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.oforsky.mmm.ebo;

public class DealCfgEboBuilder extends DealCfgEboBuilderBase<DealCfgEboBuilder> {
	public static DealCfgEboBuilder dealCfgEbo() {
		return new DealCfgEboBuilder();
	}

	public DealCfgEboBuilder() {
		super(new DealCfgEbo());
	}

	public DealCfgEbo build() {
		return getInstance();
	}
}

class DealCfgEboBuilderBase<GeneratorT extends DealCfgEboBuilderBase<GeneratorT>> {
	private DealCfgEbo instance;

	protected DealCfgEboBuilderBase(DealCfgEbo aInstance) {
		instance = aInstance;
	}

	protected DealCfgEbo getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withDayCount(Integer aValue) {
		instance.setDayCount(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withOverTimes(Integer aValue) {
		instance.setOverTimes(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withKBreak(Integer aValue) {
		instance.setKBreak(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withWinChance(Integer aValue) {
		instance.setWinChance(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withRevenueRate(Double aValue) {
		instance.setRevenueRate(aValue);

		return (GeneratorT) this;
	}
}
