// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.oforsky.mmm.ebo;

public class QueryJobEboBuilder extends
		QueryJobEboBuilderBase<QueryJobEboBuilder> {
	public static QueryJobEboBuilder queryJobEbo() {
		return new QueryJobEboBuilder();
	}

	public QueryJobEboBuilder() {
		super(new QueryJobEbo());
	}

	public QueryJobEbo build() {
		return getInstance();
	}
}

class QueryJobEboBuilderBase<GeneratorT extends QueryJobEboBuilderBase<GeneratorT>> {
	private QueryJobEbo instance;

	protected QueryJobEboBuilderBase(QueryJobEbo aInstance) {
		instance = aInstance;
	}

	protected QueryJobEbo getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withJobOid(Integer aValue) {
		instance.setJobOid(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCode(String aValue) {
		instance.setCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPrice(Double aValue) {
		instance.setPrice(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withAmount(Integer aValue) {
		instance.setAmount(aValue);

		return (GeneratorT) this;
	}
}
