// CHECKSTYLE:OFF
/**
 * Source code generated by Fluent Builders Generator
 * Do not modify this file
 * See generator home page at: http://code.google.com/p/fluent-builders-generator-eclipse-plugin/
 */

package com.oforsky.mmm.ebo;

public class StockGroupEboBuilder extends
		StockGroupEboBuilderBase<StockGroupEboBuilder> {
	public static StockGroupEboBuilder stockGroupEbo() {
		return new StockGroupEboBuilder();
	}

	public StockGroupEboBuilder() {
		super(new StockGroupEbo());
	}

	public StockGroupEbo build() {
		return getInstance();
	}
}

class StockGroupEboBuilderBase<GeneratorT extends StockGroupEboBuilderBase<GeneratorT>> {
	private StockGroupEbo instance;

	protected StockGroupEboBuilderBase(StockGroupEbo aInstance) {
		instance = aInstance;
	}

	protected StockGroupEbo getInstance() {
		return instance;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withCode(String aValue) {
		instance.setCode(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withName(String aValue) {
		instance.setName(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withStockType(StockTypeEnum aValue) {
		instance.setStockType(aValue);

		return (GeneratorT) this;
	}

	@SuppressWarnings("unchecked")
	public GeneratorT withPk(StockGroupPk aValue) {
		instance.setPk(aValue);

		return (GeneratorT) this;
	}
}
